baseURL = "https://oscarvillena.github.io/dwes/"
languageCode = "en-us"
title = "Desarrollo de aplicaciones web en el servidor"
theme = 'learn'
defaultContentLanguage = "es"
defaultContentLanguageInSubdir= true


[params]
themeVariant="blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]

name = " <i class='fab fa-php'></i> Página de Php"
identifier = "al"
url = "https://php.net"
weight = 10

[[menu.shortcuts]]

name = " <i class='fab fa-ubuntu'></i> Página de Ubuntu"
identifier = "el"
url = "https://ubuntu.com/"
weight = 10

[[menu.shortcuts]]

name = " <i class='fab fa-instagram'></i> Página de Instagram"
identifier = "ul"
url = "https://www.instagram.com/?hl=es"
weight = 10

[Languages]
[Languages.es]
title = "documentacion del tema hugo learn"
weight = 1
languageName = "Español"

[Languages.fr]
title = "Documentation du thème Hugo Learn"
weight = 2
languageName = "Français"



[[menu.shortcuts]]

name = " <i class='fab fa-youtube'></i> Página de Youtube"
identifier = "il"
url = "https://www.youtube.com/?hl=ES"
weight = 10



